# This Python file uses the following encoding: utf-8

midi_channel = 0
midi_relative = False
midi_relative_mode = 2
midi_relative_acceleration = 2.0


# GENERAL
MIDI_MODE = 9

MIDI_UTIL_TAB_INDICATOR = 17
MIDI_LAD_TAB_INDICATOR = 18
MIDI_MORPH_TAB_INDICATOR = 19
MIDI_EUC_TAB_INDICATOR = 20
MIDI_LOOP_TAB_INDICATOR = 21

# UTIL/LAD/MORPH
MIDI_LAD_LOWER_FADER = 17
MIDI_LAD_MIXER_INFO = 18
MIDI_LAD_ARM = 19
MIDI_LAD_OVD = 20
MIDI_LAD_RAND = 21
MIDI_LAD_TRACK_PLUS = 22
MIDI_LAD_DEVICE_PLUS = 23
MIDI_LAD_PAGE_PLUS = 24
MIDI_LAD_SHOW = 25
MIDI_LAD_SET_RESET = 26
MIDI_LAD_PERF = 27
MIDI_LAD_REC = 28
MIDI_LAD_MORPH = 29
MIDI_LAD_TRACK_MINUS = 30
MIDI_LAD_DEVICE_MINUS = 31
MIDI_LAD_PAGE_MINUS = 32

MIDI_LAD_PRESET1 = 11
MIDI_LAD_PRESET2 = 12
MIDI_LAD_PRESET3 = 13
MIDI_LAD_PRESET4 = 14
MIDI_LAD_PRESET5 = 15
MIDI_LAD_PRESET6 = 16

MIDI_LAD_ENCODER1 = 1
MIDI_LAD_ENCODER2 = 2
MIDI_LAD_ENCODER3 = 3
MIDI_LAD_ENCODER4 = 4
MIDI_LAD_ENCODER5 = 5
MIDI_LAD_ENCODER6 = 6
MIDI_LAD_ENCODER7 = 7
MIDI_LAD_ENCODER8 = 8

MIDI_LAD_MORPH_SLIDER = 63

# EUCLIDEAN
MIDI_EUC_ENCODER1 = 1
MIDI_EUC_ENCODER2 = 2
MIDI_EUC_ENCODER3 = 3

MIDI_EUC_CURNOTE1 = 17
MIDI_EUC_CURNOTE2 = 18
MIDI_EUC_CURNOTE3 = 19
MIDI_EUC_CURNOTE4 = 20
MIDI_EUC_CURNOTE5 = 21
MIDI_EUC_CURNOTE6 = 22
MIDI_EUC_CURNOTE7 = 23
MIDI_EUC_CURNOTE8 = 24

MIDI_EUC_PLAY1 = 25
MIDI_EUC_PLAY2 = 26
MIDI_EUC_PLAY3 = 27
MIDI_EUC_PLAY4 = 28
MIDI_EUC_PLAY5 = 29
MIDI_EUC_PLAY6 = 30
MIDI_EUC_PLAY7 = 31
MIDI_EUC_PLAY8 = 32

# LOOP
MIDI_LOOP_START_MEAS_ENCODER = 1
MIDI_LOOP_START_BEAT_ENCODER = 2
MIDI_LOOP_START_QBEAT_ENCODER = 3
MIDI_LOOP_END_MEAS_ENCODER = 4
MIDI_LOOP_END_BEAT_ENCODER = 5
MIDI_LOOP_END_QBEAT_ENCODER = 6
MIDI_LOOP_PITCH_ENCODER = 7

MIDI_LOOP_UPP1 = 17
MIDI_LOOP_UPP2 = 18
MIDI_LOOP_UPP3 = 19
MIDI_LOOP_UPP4 = 20
MIDI_LOOP_UPP5 = 21
MIDI_LOOP_UPP6 = 22
MIDI_LOOP_UPP7 = 23
MIDI_LOOP_UPP8 = 24

MIDI_LOOP_LOW1 = 25
MIDI_LOOP_LOW2 = 26
MIDI_LOOP_LOW3 = 27
MIDI_LOOP_LOW4 = 28
MIDI_LOOP_LOW5 = 29
MIDI_LOOP_LOW6 = 30
MIDI_LOOP_LOW7 = 31
MIDI_LOOP_LOW8 = 32

MIDI_LOOP_TOGGLE_PRESET_MODE = 11
MIDI_LOOP_RAND = 12
MIDI_LOOP_CALL_PITCH = 15
MIDI_LOOP_SET_PITCH = 16

MIDI_LOOP_MORPH_SLIDER = 63
