# This Python file uses the following encoding: utf-8

midi_channel = 0
midi_relative = False
midi_relative_mode = 2
midi_relative_acceleration = 2.0


# GENERAL
MIDI_MODE = -1
MIDI_LOAD_CFG = -1

MIDI_UTIL_TAB_INDICATOR = -1
MIDI_LAD_TAB_INDICATOR = -1
MIDI_MORPH_TAB_INDICATOR = -1
MIDI_EUC_TAB_INDICATOR = -1
MIDI_LOOP_TAB_INDICATOR = -1

# UTIL/LAD/MORPH
MIDI_LAD_LOWER_FADER = -1
MIDI_LAD_MIXER_INFO = -1
MIDI_LAD_ARM = -1
MIDI_LAD_OVD = -1
MIDI_LAD_RAND = -1
MIDI_LAD_TRACK_PLUS = -1
MIDI_LAD_DEVICE_PLUS = -1
MIDI_LAD_PAGE_PLUS = -1
MIDI_LAD_SHOW = -1
MIDI_LAD_SET_RESET = -1
MIDI_LAD_PERF = -1
MIDI_LAD_REC = -1
MIDI_LAD_MORPH = -1
MIDI_LAD_TRACK_MINUS = -1
MIDI_LAD_DEVICE_MINUS = -1
MIDI_LAD_PAGE_MINUS = -1

MIDI_LAD_PRESET1 = -1
MIDI_LAD_PRESET2 = -1
MIDI_LAD_PRESET3 = -1
MIDI_LAD_PRESET4 = -1
MIDI_LAD_PRESET5 = -1
MIDI_LAD_PRESET6 = -1

MIDI_LAD_ENCODER1 = -1
MIDI_LAD_ENCODER2 = -1
MIDI_LAD_ENCODER3 = -1
MIDI_LAD_ENCODER4 = -1
MIDI_LAD_ENCODER5 = -1
MIDI_LAD_ENCODER6 = -1
MIDI_LAD_ENCODER7 = -1
MIDI_LAD_ENCODER8 = -1

MIDI_LAD_MORPH_SLIDER = -1

# EUCLIDEAN
MIDI_EUC_ENCODER1 = -1
MIDI_EUC_ENCODER2 = -1
MIDI_EUC_ENCODER3 = -1

MIDI_EUC_CURNOTE1 = -1
MIDI_EUC_CURNOTE2 = -1
MIDI_EUC_CURNOTE3 = -1
MIDI_EUC_CURNOTE4 = -1
MIDI_EUC_CURNOTE5 = -1
MIDI_EUC_CURNOTE6 = -1
MIDI_EUC_CURNOTE7 = -1
MIDI_EUC_CURNOTE8 = -1

MIDI_EUC_PLAY1 = -1
MIDI_EUC_PLAY2 = -1
MIDI_EUC_PLAY3 = -1
MIDI_EUC_PLAY4 = -1
MIDI_EUC_PLAY5 = -1
MIDI_EUC_PLAY6 = -1
MIDI_EUC_PLAY7 = -1
MIDI_EUC_PLAY8 = -1

# LOOP
MIDI_LOOP_START_MEAS_ENCODER = -1
MIDI_LOOP_START_BEAT_ENCODER = -1
MIDI_LOOP_START_QBEAT_ENCODER = -1
MIDI_LOOP_END_MEAS_ENCODER = -1
MIDI_LOOP_END_BEAT_ENCODER = -1
MIDI_LOOP_END_QBEAT_ENCODER = -1
MIDI_LOOP_PITCH_ENCODER = -1

MIDI_LOOP_UPP1 = -1
MIDI_LOOP_UPP2 = -1
MIDI_LOOP_UPP3 = -1
MIDI_LOOP_UPP4 = -1
MIDI_LOOP_UPP5 = -1
MIDI_LOOP_UPP6 = -1
MIDI_LOOP_UPP7 = -1
MIDI_LOOP_UPP8 = -1

MIDI_LOOP_LOW1 = -1
MIDI_LOOP_LOW2 = -1
MIDI_LOOP_LOW3 = -1
MIDI_LOOP_LOW4 = -1
MIDI_LOOP_LOW5 = -1
MIDI_LOOP_LOW6 = -1
MIDI_LOOP_LOW7 = -1
MIDI_LOOP_LOW8 = -1

MIDI_LOOP_TOGGLE_PRESET_MODE = -1
MIDI_LOOP_RAND = -1
MIDI_LOOP_CALL_PITCH = -1
MIDI_LOOP_SET_PITCH = -1

MIDI_LOOP_MORPH_SLIDER = -1
